version: "3.8"

services:
  ddev-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: ddev-dev
    tty: true
    stdin_open: true
    privileged: true
    working_dir: /home/ubuntu/dd
    environment:
      - PATH=/home/ubuntu/.local/bin:$PATH
      - DOCKER_GID=${DOCKER_GID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: "ubuntu:${DOCKER_GID}"
